- hosts: nginx
  tasks:
    - name: Install Nginx
      package:
        name: nginx
        state: latest
    - name: Copy file with owner and permissions
      copy:
        src: index.html
        dest: /var/www/html/index.nginx-debian.html
        owner: root
        group: root
        mode: '0644'
        become: yes
